# Generated by Django 2.1.7 on 2022-04-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=250)),
                ('title_x', models.CharField(max_length=500)),
                ('categories', models.CharField(max_length=200, null=True)),
                ('author', models.CharField(max_length=100, null=True)),
                ('description_x', models.TextField(max_length=2000, null=True)),
                ('image', models.CharField(max_length=264, null=True)),
                ('audio_length', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(default=1970)),
                ('watched', models.BooleanField(default=False, null=True)),
                ('recommended', models.BooleanField(default=False, null=True)),
                ('audio', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
