# Generated by Django 4.0.3 on 2022-03-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcastrecommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='pub_date',
            field=models.DateTimeField(default=1970),
        ),
    ]
