# Generated by Django 2.1.7 on 2022-04-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcastrecommender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Views1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
