# Generated by Django 2.1.7 on 2022-04-17 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcastrecommender', '0002_views1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Views1',
        ),
    ]
